### PR TITLE
Update Browser-Extension-For-BugBounty-Hunters.md

### PR DESCRIPTION
**Pull request by Sevada797**
This extension helps keeping multiple sessions alive at the same time, by so it can help cyber-security researchers or bug hunters in their pen-testing for bugs like IDOR or cross account authorization flaws and etc bugs...

### CODE REVIEW

**Comment by Sevada797** [comment]
Hey I am from Medium, sorry for late pull request )

**Comment by Raunaksplanet** [comment]
Hey whatsuppp!!! how are you ?  Thanks for the contribution man appreciated

**Comment by Sevada797** [comment]
Good thanks, BTW recently had my first bug bounty at Hackerone 😁
Want to do a writeup, but the issue isn't resolved, can't disclose yet :/
Tho 2 weeks passed.
How are you doing?

**Comment by Raunaksplanet** [comment]
I'm doing good buddy, Congrats on you first finding, I haven't found anything yet 😅. Waiting for your Writeup !!!!

**Comment by Raunaksplanet** [comment]
Share you linkedin, twitter lets connect there

**Pull request merged**
